/**
 * piano_songs.js — 50 bài hát thiếu nhi (PD / dân gian / giai điệu giáo dục gốc).
 * 20 dễ · 20 vừa · 10 khó. Chỉ phím trắng C–C5.
 */
function S(id, title, difficulty, tempo, notes, durs) {
    return {
        id, title, difficulty, tempo,
        timeSignature: '4/4',
        notes,
        durs: durs || notes.map(() => 'q'),
        origin: 'pd',
    };
}

const BUNNY_PIANO_SONGS = [
    S('song-01', 'Bánh nóng', 1, 80,
        ['E', 'D', 'C', 'E', 'D', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'D', 'C']),
    S('song-02', 'Cừu nhỏ của Mary', 1, 84,
        ['E', 'D', 'C', 'D', 'E', 'E', 'E', 'D', 'D', 'D', 'E', 'G', 'G']),
    S('song-03', 'Chèo thuyền nhẹ', 1, 84,
        ['G', 'E', 'E', 'F', 'D', 'D', 'C', 'D', 'E', 'F', 'G', 'G', 'G']),
    S('song-04', 'Mưa ơi mưa', 1, 80,
        ['G', 'G', 'E', 'E', 'D', 'D', 'C', 'G', 'G', 'E', 'E', 'D', 'C']),
    S('song-05', 'Sao lấp lánh', 1, 80,
        ['C', 'C', 'G', 'G', 'F', 'F', 'E', 'E', 'D', 'D', 'C']),
    S('song-06', 'Ánh trăng êm', 1, 76,
        ['C', 'C', 'C', 'D', 'E', 'D', 'C', 'E', 'D', 'D', 'C']),
    S('song-07', 'Kể với dì', 1, 84,
        ['E', 'G', 'G', 'G', 'E', 'D', 'C', 'D', 'E', 'G', 'G', 'E', 'D', 'C']),
    S('song-08', 'Người bán bánh', 1, 88,
        ['C', 'E', 'G', 'G', 'E', 'C', 'D', 'E', 'D', 'C']),
    S('song-09', 'Đồng hồ tích tắc', 1, 88,
        ['C', 'C', 'D', 'E', 'C', 'G', 'E', 'C', 'D', 'E', 'C']),
    S('song-10', 'Cầu London', 1, 84,
        ['G', 'F', 'E', 'F', 'G', 'D', 'E', 'F', 'E', 'F', 'G']),
    S('song-11', 'Chèo thuyền nào', 1, 80,
        ['C', 'C', 'C', 'D', 'E', 'E', 'D', 'E', 'F', 'G']),
    S('song-12', 'Jacques ngủ chưa', 1, 84,
        ['C', 'D', 'E', 'C', 'C', 'D', 'E', 'C', 'E', 'F', 'G']),
    S('song-13', 'Khúc vui', 1, 88,
        ['E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E']),
    S('song-14', 'Chuông reo', 1, 96,
        ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'D', 'E']),
    S('song-15', 'Ông già này', 1, 88,
        ['G', 'E', 'G', 'G', 'E', 'G', 'F', 'E', 'D', 'C']),
    S('song-16', 'Cò bay', 1, 80,
        ['C', 'D', 'E', 'G', 'E', 'D', 'C', 'E', 'G', 'E', 'C']),
    S('song-17', 'Năm ngón tay', 1, 84,
        ['C', 'D', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C']),
    S('song-18', 'Ong vàng', 1, 88,
        ['G', 'E', 'C', 'E', 'G', 'G', 'E', 'C', 'D', 'E', 'C']),
    S('song-19', 'Gà con', 1, 84,
        ['C', 'C', 'E', 'E', 'G', 'E', 'C', 'D', 'D', 'C']),
    S('song-20', 'Vỗ tay nào', 1, 92,
        ['C', 'E', 'G', 'E', 'C', 'E', 'G', 'G', 'E', 'C']),

    S('song-21', 'Cừu Mary (cả bài)', 2, 88,
        ['E', 'D', 'C', 'D', 'E', 'E', 'E', 'D', 'D', 'D', 'E', 'G', 'G',
            'E', 'D', 'C', 'D', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'D', 'C']),
    S('song-22', 'Sao lấp lánh (đoạn A)', 2, 84,
        ['C', 'C', 'G', 'G', 'A', 'A', 'G', 'F', 'F', 'E', 'E', 'D', 'D', 'C']),
    S('song-23', 'Cầu London (cả khúc)', 2, 88,
        ['G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'E', 'F', 'E', 'F', 'G',
            'G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'G', 'E', 'C']),
    S('song-24', 'Chèo thuyền trên sông', 2, 80,
        ['C', 'C', 'C', 'D', 'E', 'E', 'D', 'E', 'F', 'G',
            'C', 'C', 'C', 'G', 'G', 'G', 'E', 'E', 'E', 'C', 'C', 'C', 'G', 'F', 'E', 'D', 'C']),
    S('song-25', 'Jacques ơi dậy đi', 2, 88,
        ['C', 'D', 'E', 'C', 'C', 'D', 'E', 'C', 'E', 'F', 'G', 'E', 'F', 'G',
            'G', 'A', 'G', 'F', 'E', 'C', 'G', 'A', 'G', 'F', 'E', 'C', 'C', 'G', 'C']),
    S('song-26', 'Chèo thuyền nhẹ (đủ)', 2, 88,
        ['G', 'E', 'E', 'F', 'D', 'D', 'C', 'D', 'E', 'F', 'G', 'G', 'G',
            'G', 'E', 'E', 'F', 'D', 'D', 'C', 'E', 'G', 'G', 'C']),
    S('song-27', 'Chuông Giáng Sinh', 2, 100,
        ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'D', 'E',
            'F', 'F', 'F', 'F', 'F', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'D', 'G']),
    S('song-28', 'Khúc ca vui', 2, 92,
        ['E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E', 'E', 'D', 'D',
            'E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E', 'D', 'C', 'C']),
    S('song-29', 'Nông trại ông Mac', 2, 96,
        ['C', 'C', 'C', 'G', 'A', 'A', 'G', 'E', 'E', 'D', 'D', 'C',
            'G', 'C', 'C', 'C', 'G', 'A', 'A', 'G']),
    S('song-30', 'Nông dân trong thung', 2, 92,
        ['C', 'C', 'C', 'G', 'A', 'A', 'G', 'E', 'E', 'D', 'D', 'C', 'G', 'E', 'C']),
    S('song-31', 'Nhảy cùng Lou', 2, 96,
        ['C', 'C', 'D', 'E', 'C', 'E', 'D', 'G', 'C', 'C', 'D', 'E', 'C', 'G', 'E', 'C']),
    S('song-32', 'Bụi dâu vòng quanh', 2, 92,
        ['G', 'G', 'A', 'G', 'E', 'C', 'D', 'E', 'G', 'G', 'A', 'G', 'E', 'C']),
    S('song-33', 'Ông già đếm số', 2, 92,
        ['G', 'E', 'G', 'G', 'E', 'G', 'A', 'G', 'E', 'D', 'C', 'D', 'E', 'C']),
    S('song-34', 'Kể với dì Rhody', 2, 88,
        ['E', 'G', 'G', 'G', 'E', 'D', 'C', 'D', 'E', 'G', 'G', 'E', 'D', 'C',
            'E', 'G', 'A', 'G', 'E', 'D', 'C']),
    S('song-35', 'Ánh trăng dịu dàng', 2, 76,
        ['C', 'C', 'C', 'D', 'E', 'D', 'C', 'E', 'D', 'D', 'C',
            'C', 'C', 'C', 'D', 'E', 'D', 'C', 'E', 'D', 'C']),
    S('song-36', 'Ngủ chưa bạn ơi', 2, 88,
        ['C', 'D', 'E', 'C', 'C', 'D', 'E', 'C', 'E', 'F', 'G', 'E', 'F', 'G', 'G', 'A', 'G', 'E', 'C']),
    S('song-37', 'Yankee Doodle', 2, 100,
        ['C', 'C', 'D', 'E', 'C', 'E', 'D', 'G', 'C', 'C', 'D', 'E', 'C', 'A', 'G']),
    S('song-38', 'Camptown', 2, 96,
        ['G', 'G', 'E', 'G', 'A', 'G', 'E', 'C', 'D', 'E', 'D', 'C']),
    S('song-39', 'Các thánh bước vào', 2, 92,
        ['C', 'E', 'F', 'G', 'C', 'E', 'F', 'G', 'C', 'E', 'F', 'G', 'E', 'C', 'E', 'D']),
    S('song-40', 'Cô ấy sắp tới', 2, 96,
        ['C', 'D', 'E', 'C', 'E', 'D', 'G', 'C', 'D', 'E', 'C', 'G', 'E', 'C']),

    S('song-41', 'Sao lấp lánh (cả bài)', 3, 88,
        ['C', 'C', 'G', 'G', 'A', 'A', 'G', 'F', 'F', 'E', 'E', 'D', 'D', 'C',
            'G', 'G', 'F', 'F', 'E', 'E', 'D', 'G', 'G', 'F', 'F', 'E', 'E', 'D',
            'C', 'C', 'G', 'G', 'A', 'A', 'G', 'F', 'F', 'E', 'E', 'D', 'D', 'C']),
    S('song-42', 'Khúc ca vui (đủ)', 3, 96,
        ['E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E', 'E', 'D', 'D',
            'E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E', 'D', 'C', 'C',
            'D', 'D', 'E', 'C', 'D', 'E', 'F', 'E', 'C', 'D', 'E', 'F', 'E', 'D', 'C', 'G', 'C']),
    S('song-43', 'Chuông Giáng Sinh (đủ)', 3, 104,
        ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'D', 'E',
            'F', 'F', 'F', 'F', 'F', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'D', 'G',
            'E', 'E', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'D', 'E',
            'F', 'F', 'F', 'F', 'F', 'E', 'E', 'E', 'G', 'G', 'F', 'D', 'C']),
    S('song-44', 'Cầu London (lặp)', 3, 92,
        ['G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'E', 'F', 'E', 'F', 'G',
            'G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'G', 'E', 'C',
            'G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'E', 'F', 'E', 'F', 'G', 'D', 'G', 'E', 'C']),
    S('song-45', 'Jacques ơi (cả vòng)', 3, 92,
        ['C', 'D', 'E', 'C', 'C', 'D', 'E', 'C', 'E', 'F', 'G', 'E', 'F', 'G',
            'G', 'A', 'G', 'F', 'E', 'C', 'G', 'A', 'G', 'F', 'E', 'C',
            'C', 'G', 'C', 'C', 'G', 'C', 'E', 'G', 'C5', 'G', 'E', 'C']),
    S('song-46', 'Ô Susanna', 3, 100,
        ['C', 'D', 'E', 'G', 'G', 'A', 'G', 'E', 'C', 'D', 'E', 'E', 'D', 'C', 'D',
            'C', 'D', 'E', 'G', 'G', 'A', 'G', 'E', 'C', 'D', 'E', 'D', 'C', 'C']),
    S('song-47', 'Ru con Brahms', 3, 72,
        ['E', 'E', 'G', 'E', 'E', 'G', 'E', 'G', 'C5', 'A', 'A', 'G',
            'D', 'F', 'A', 'G', 'D', 'F', 'A', 'G', 'D', 'G', 'F', 'D', 'C']),
    S('song-48', 'Minuet vườn thỏ', 3, 96,
        ['G', 'E', 'G', 'C5', 'B', 'A', 'G', 'F', 'E', 'D', 'C', 'D', 'E', 'F', 'G',
            'G', 'E', 'G', 'C5', 'B', 'A', 'G', 'E', 'C', 'D', 'E', 'D', 'C']),
    S('song-49', 'Các thánh bước vào (đủ)', 3, 96,
        ['C', 'E', 'F', 'G', 'C', 'E', 'F', 'G', 'C', 'E', 'F', 'G', 'E', 'C', 'E', 'D',
            'C', 'E', 'F', 'G', 'A', 'A', 'A', 'F', 'G', 'E', 'C', 'D', 'C']),
    S('song-50', 'Chúc mừng sinh nhật', 3, 88,
        ['C', 'C', 'D', 'C', 'F', 'E', 'C', 'C', 'D', 'C', 'G', 'F',
            'C', 'C', 'C5', 'A', 'F', 'E', 'D', 'A', 'A', 'F', 'G', 'F']),
];

const BunnyPianoSongs = {
    RAW: BUNNY_PIANO_SONGS,
    all() { return BUNNY_PIANO_SONGS.slice(); },
};

if (typeof module !== 'undefined') module.exports = { BunnyPianoSongs, BUNNY_PIANO_SONGS };
